version: "3.9"  # optional since v1.27.0
services:
  user_ms:
    container_name: firma_user_ms
    build: ./firma_user_ms
    ports:
      - 8090:8090
  docs_ms:
    container_name: firma_docs_ms   
    build: ./firma_docs_ms
    volumes:
      - ./firma_docs_ms/src:/usr/src/app/src
    ports:
      - 8091:3000      
  storage_ms:
    container_name: firma_storage_ms    
    build: ./firma_storage_ms
    volumes:
      - ./firma_storage_ms/src:/usr/src/app/src
    ports:
      - 8092:8000      
  keys_ms:
    container_name: firma_keys_ms    
    build: ./firma_keys_ms
    volumes:
      - ./firma_keys_ms/src:/usr/src/app/src
    ports:
      - 8093:8093      
  signing_ms:
    container_name: firma_signing_ms
    build: ./firma_signing_ms/
    volumes:
      - ./firma_signing_ms/src:/var/www/html/
    ports:
      - 8095:80      
    networks:
      - default
    links:
      - mq                
  mq:
    container_name: firma_mq   
    build: ./firma_mq
    environment:
      - RABBITMQ_DEFAULT_USER=myuser
      - RABBITMQ_DEFAULT_PASS=mypassword    
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - default   
  ag:
    container_name: firma_ag   
    build: ./firma_ag
    volumes:
      - ./firma_ag/src:/usr/src/app/src
    ports:
      - 80:80
    networks:
      - default
    links:
      - mq         